Update admindocs refs to Singularity community links
hpcng/singularity-admindocs pull request #120
Opened 2021-06-29 02:04 UTC by pedroalvesbatista

### Description of the Pull Request (PR):
Updates references to point to Singularity Community admin docs.

### Before submitting a PR, make sure you have done the following:
Read the Guidelines for Contributing, and this PR conforms to the stated requirements.
Added changes to the CHANGELOG if necessary according to the Contribution Guidelines
Added tests to validate this PR, linted with make check and tested this PR locally with a make test, and make testall if possible (see CONTRIBUTING.md).
Based this PR against the appropriate branch according to the Contribution Guidelines
Added myself as a contributor to the Contributors File

2021-06-29 18:34 UTC, DrDaveD requested changes
Please replace all the `user-docs/master` with `user-docs/\{userversion\}` and `admin-docs/master` with `admin-docs/\{adminversion\}`.  We do have those macros, and it would be better to point to the same version than the master branch.

2021-06-29 18:34 UTC, DrDaveD commented on security.rst
> +discovered vulnerabilities and update when necessary just as they would with any other software. Singularity Security Team is constantly probing to
```suggestion
discovered vulnerabilities and update when necessary just as they would with any other software. The Singularity community is constantly probing to 
```

2021-06-29 23:23 UTC, pedroalvesbatista commented
> Please replace all the `user-docs/master` with `user-docs/\{userversion\}` and `admin-docs/master` with `admin-docs/\{adminversion\}`. We do have those macros, and it would be better to point to the same version than the master branch.

Alright, done !

2021-06-30 14:19 UTC, DrDaveD requested changes
Now it lost all the "user-docs" before the `/\{userversion\}` and the `admin-docs` before the `/\{adminversion\}`.  I also still see one case of `admin-docs/master`.  Please fix.

2021-06-30 14:21 UTC, DrDaveD commented on security.rst
> +Singularity Community addresses container security as a continuous process. It attempts to provide container integrity throughout the distribution
```suggestion
The Singularity community addresses container security as a continuous process. It attempts to provide container integrity throughout the distribution
```

2021-06-30 17:55 UTC, pedroalvesbatista commented
> Now it lost all the "user-docs" before the `/\{userversion\}` and the `admin-docs` before the `/\{adminversion\}`. I also still see one case of `admin-docs/master`. Please fix.

Done !

2021-06-30 19:18 UTC, DrDaveD approved these changes

2021-06-30 19:19 UTC, merged